Dev 47
cherryontech/squad-debugging-darlings pull request #53
Opened 2023-04-05 18:45 UTC by ajkarczewski

### What (if any) features are you implementing?
- Created UI and route for the Industry Selection component

### What (if anything) did you refactor?
- N/A
### Were there any issues that arose?
- N/A

### Refactor checklist
- [x] Check variable and parameter names: are they descriptive and unique?
- [x] Is the code DRY? SRP?
- [x] Is it easy for others to read your code? (explanatory comments needed?)
- [x] Is the syntax consistent? (e.g. use of semicolons, blank lines)
- [x ] Are commit messages formatted correctly?

2023-04-05 19:52 UTC, YashsviG requested changes
Please add get and patch requests from the BE to have the data saved in the db

2023-04-05 20:55 UTC, YashsviG commented on frontend/src/App.js
> +          <Route path="/industry-selection" element={<IndustrySelection matchedWith="mentor" industryQuestion="Select up to 5 industries of interest!" />} />
follow the same pathing we are doing for the rest of the components

2023-04-08 19:04 UTC, YashsviG commented on frontend/src/Components/RoleSelection.js
> +       }
we can just do else block like:
```suggestion
       } else {
         navigate("/mentee-flow-2");
       }
```

2023-04-08 19:04 UTC, YashsviG commented on frontend/src/Components/IndustrySelection.js
> +      console.log(response.data);
TODO: Need to add a navigate here for the upcoming flow-3
navigate('mentor/mentee-flow-3')

2023-04-08 19:35 UTC, ajkarczewski commented on frontend/src/App.js
> +import IndustrySelection from "./Components/IndustrySelection";
can you clarify what you mean in the first part?

2023-04-15 16:37 UTC, YashsviG reviewed
Some small stuff to fix other than that looks good :))
Do you have the CSS all in place? or still working on it?

2023-04-15 16:37 UTC, YashsviG commented on frontend/src/App.js
> +        />
Love the clean up you have done in this file :))

2023-04-15 16:37 UTC, YashsviG commented on frontend/src/Components/RoleSelection.js
> +const TitleSelection = ({ question, matchedWith }) => {
Change the name of the file to TitleSelection as well

2023-04-16 17:28 UTC, YashsviG approved these changes

2023-04-16 17:29 UTC, merged